import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:net';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { boundaryViolations } from '../../../tools/check-boundaries.mjs';
import { findCycles } from '../../../tools/check-cycles.mjs';

test('autorise les imports par point d entree public dans le sens attendu', () => {
  assert.deepEqual(boundaryViolations([
    { from: 'packages/screens/src/index.ts', fromOwner: 'screens', target: '@project/domains', targetOwner: 'domains', deep: false, crossRelative: false },
    { from: 'packages/screens/src/index.tsx', fromOwner: 'screens', target: './app-shell', targetOwner: 'screens', deep: false, crossRelative: false },
  ]), []);
});

test('refuse les imports profonds et les directions interdites', () => {
  const violations = boundaryViolations([
    { from: 'packages/screens/src/index.ts', fromOwner: 'screens', target: '@project/domains/internal', targetOwner: 'domains', deep: true, crossRelative: false },
    { from: 'packages/domains/src/index.ts', fromOwner: 'domains', target: '@project/ui', targetOwner: 'ui', deep: false, crossRelative: false },
    { from: 'packages/screens/src/index.ts', fromOwner: 'screens', target: 'tamagui', targetOwner: null, deep: false, crossRelative: false },
    { from: 'packages/screens/src/index.ts', fromOwner: 'screens', target: '@project/router', targetOwner: 'router', deep: false, crossRelative: false }
  ]);
  assert.equal(violations.length, 4);
});

test('refuse les cycles', () => {
  assert.deepEqual(findCycles({ screens: ['domains'], domains: ['screens'] }), ['screens -> domains -> screens']);
});

test('centralise les invariants d authentification sans identifiant par defaut', async () => {
  const { readFile } = await import('node:fs/promises');
  const migration = await readFile('apps/api/database/migrations/20260827000000_create_authentication_tables.ts', 'utf8');
  const auth = await readFile('apps/api/app/auth.ts', 'utf8');
  const policy = await readFile('apps/api/app/auth_policy.mjs', 'utf8');
  const controller = await readFile('apps/api/app/auth_controller.ts', 'utf8');
  assert.match(migration, /createTable\('accounts'/);
  assert.match(migration, /createTable\('login_attempts'/);
  assert.match(migration, /createTable\('sessions'/);
  assert.match(migration, /createTable\('security_audit_proofs'/);
  assert.match(policy, /normalize\('NFKC'\)/);
  assert.match(auth, /MAX_ATTEMPTS = 5/);
  assert.match(auth, /GENERIC_DELAY_MS = 350/);
  assert.match(auth, /login_succeeded/);
  assert.match(auth, /login_refused/);
  assert.match(controller, /sameCsrfToken/);
  assert.match(controller, /auth\.use\('web'\)\.logout/);
  assert.doesNotMatch(auth + migration + controller, /example\.com|password\s*=\s*['"]/i);
});

test('reproduit le workspace depuis son lockfile racine unique', async () => {
  const { access, readFile } = await import('node:fs/promises');
  await access('pnpm-lock.yaml');
  const manifest = JSON.parse(await readFile('package.json', 'utf8'));
  assert.equal(manifest.packageManager, 'pnpm@10.14.0');
  assert.equal(manifest.engines.node, '24.0.0');
});

test('le contrat santé définit ses réponses et problèmes à la frontière', async () => {
  const { readFile } = await import('node:fs/promises');
  const contract = await readFile('apps/api/openapi/v1.yaml', 'utf8');
  const client = await readFile('packages/api-client/src/index.ts', 'utf8');
  assert.match(contract, /^openapi: 3\.1\.2$/m);
  assert.match(contract, /status:\n\s+type: string\n\s+const: ok/);
  assert.match(contract, /'404':\n\s+\$ref: '#\/components\/responses\/Problem'/);
  assert.match(contract, /required: \[type, title, status, detail, correlationId\]/);
  assert.match(contract, /minimum: 400\n\s+maximum: 599/);
  assert.match(contract, /pattern: '\^\[A-Za-z0-9-\]\{1,128\}\$'/);
  assert.match(client, /auto-generated by openapi-typescript/);
  assert.match(client, /getHealth/);
});

test('la santé ne révèle aucun détail et les erreurs sont des problèmes RFC 9457 corrélés', async () => {
  const { readFile } = await import('node:fs/promises');
  const source = await readFile('apps/api/app/http.ts', 'utf8');
  assert.match(source, /body: \{ status: 'ok' \}/);
  assert.match(source, /'application\/problem\+json'/);
  assert.match(source, /correlationId: correlationId\(requestId\)/);
});

test('le listener Adonis expose la santé avec la corrélation fournie', async () => {
  const port = await new Promise((resolve, reject) => {
    const server = createServer();
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      server.close((error) => error ? reject(error) : resolve(address.port));
    });
  });
  const child = spawn(process.execPath, ['--import', 'ts-node-maintained/register/esm', 'bin/server.ts'], {
    cwd: 'apps/api',
    env: {
      ...process.env,
      APP_KEY: `${randomUUID()}${randomUUID()}`,
      HOST: '127.0.0.1',
      PORT: String(port),
      NODE_ENV: 'test',
      LOG_LEVEL: 'silent',
    },
    stdio: 'pipe',
  });
  let output = '';
  child.stdout.on('data', (chunk) => { output += chunk; });
  child.stderr.on('data', (chunk) => { output += chunk; });

  try {
    let response;
    for (let attempt = 0; attempt < 200; attempt += 1) {
      try {
        response = await fetch(`http://127.0.0.1:${port}/v1/health`, {
          headers: { 'X-Correlation-Id': 'test-correlation' },
        });
        break;
      } catch {
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
    }
    assert.ok(response, `Le listener Adonis ne démarre pas: ${output}`);
    assert.equal(response.status, 200);
    assert.match(response.headers.get('content-type') ?? '', /^application\/json/);
    assert.equal(response.headers.get('x-correlation-id'), 'test-correlation');
    assert.deepEqual(await response.json(), { status: 'ok' });

    for (const [name, request] of [
      ['csrf', fetch(`http://127.0.0.1:${port}/v1/auth/csrf`)],
      ['logout', fetch(`http://127.0.0.1:${port}/v1/auth/logout`, { method: 'POST' })],
    ]) {
      const protectedResponse = await request;
      const protectedBody = await protectedResponse.text();
      assert.equal(protectedResponse.status, 401, `${name}: ${protectedBody}`);
      assert.match(protectedResponse.headers.get('content-type') ?? '', /^application\/problem\+json/);
      const body = JSON.parse(protectedBody);
      assert.equal(body.status, 401);
      assert.doesNotMatch(JSON.stringify(body), /cookie|token|password|hash/i);
    }
  } finally {
    child.kill('SIGTERM');
    await new Promise((resolve) => child.once('exit', resolve));
  }
});

test('la gate de notice bloque indépendamment chaque exigence de production', async () => {
  const { resolveCollectionNoticeGate } = await import('../../ui/src/components/feedback/notice.mjs');
  assert.equal(resolveCollectionNoticeGate('production', undefined).canSubmit, false);
  const notice = {
    active: true,
    legallyValidated: true,
    version: '2026-08',
    controller: 'La Cabane du Merle',
    purpose: 'Gérer une demande',
    legalBasis: 'Exécution du contrat',
    retention: 'Durée nécessaire au traitement',
    rights: 'Accès et rectification',
    contact: 'contact@example.test',
  };
  const gate = resolveCollectionNoticeGate('production', notice);
  assert.equal(gate.canSubmit, true);
  assert.equal(gate.proofVersion, notice.version);
  for (const field of ['version', 'controller', 'purpose', 'legalBasis', 'retention', 'rights', 'contact']) {
    assert.equal(resolveCollectionNoticeGate('production', { ...notice, [field]: '' }).canSubmit, false, field);
    assert.equal(resolveCollectionNoticeGate('production', { ...notice, [field]: '   ' }).canSubmit, false, `${field} espaces`);
  }
  assert.equal(resolveCollectionNoticeGate('production', { ...notice, active: false }).canSubmit, false);
  assert.equal(resolveCollectionNoticeGate('production', { ...notice, active: 1 }).canSubmit, false);
  assert.equal(resolveCollectionNoticeGate('production', { ...notice, legallyValidated: false }).canSubmit, false);
  assert.equal(resolveCollectionNoticeGate('production', { ...notice, legallyValidated: 'true' }).canSubmit, false);
  assert.equal(resolveCollectionNoticeGate('development', undefined).canSubmit, true);
});

test('les tokens UX-DR1 à UX-DR17 centralisent les valeurs du shell', async () => {
  const { readFile } = await import('node:fs/promises');
  const source = await readFile('packages/ui/src/config.ts', 'utf8');
  const components = await Promise.all([
    'layout/screen/screen.tsx',
    'layout/screen/screen-header-frame.tsx',
    'layout/screen/sticky-action-bar.tsx',
    'components/accessibility/focus-link.tsx',
    'components/feedback/collection-notice-gate-view.tsx',
  ].map((file) => readFile(`packages/ui/src/${file}`, 'utf8')));
  const componentSource = components.join('\n');
  for (const value of [
    '#F7F6F1', '#FFFFFF', '#ECEBE3', '#1D2A1F', '#536055', '#8A928B',
    '#D7D9D1', '#285B35', '#1D4728', '#216E39', '#8A5A00', '#A9362A', '#245D85',
  ]) assert.match(source, new RegExp(value));
  for (const value of ['fontSize: 28', 'lineHeight: 34', 'fontSize: 22', 'letterSpacing: \'0.04em\'', 'xs: 4', 'xxxl: 48', 'sm: 8', 'md: 12', 'lg: 16', 'full: 9999']) {
    assert.match(source, new RegExp(value));
  }
  assert.match(componentSource, /backgroundColor: '\$surface-base'/);
  assert.match(componentSource, /backgroundColor: '\$surface-raised'/);
  assert.match(componentSource, /borderColor: '\$border-subtle'/);
  assert.match(componentSource, /outlineColor: '\$focus-ring'/);
  assert.doesNotMatch(componentSource, /overflow: 'scroll'/);
  assert.match(componentSource, /flexWrap: 'wrap'/);
  for (const value of [
    'Responsable: {gate.notice.controller}',
    'Finalité: {gate.notice.purpose}',
    'Base légale: {gate.notice.legalBasis}',
    'Durée de conservation: {gate.notice.retention}',
    'Droits: {gate.notice.rights}',
    'Contact: {gate.notice.contact}',
    'Version {gate.proofVersion}',
  ]) assert.ok(componentSource.includes(value), value);
});

test('le web génère et charge les styles Tamagui avant le build Next', async () => {
  const { readFile } = await import('node:fs/promises');
  const [manifest, buildConfig, layout, css, nextConfig, shell, button, fieldLabel, textInput, login] = await Promise.all([
    readFile('apps/web/package.json', 'utf8'),
    readFile('apps/web/tamagui.build.ts', 'utf8'),
    readFile('apps/web/src/app/layout.tsx', 'utf8'),
    readFile('apps/web/src/app/tamagui.generated.css', 'utf8'),
    readFile('apps/web/next.config.mjs', 'utf8'),
    readFile('packages/screens/src/app-shell.tsx', 'utf8'),
    readFile('packages/ui/src/components/button/button.tsx', 'utf8'),
    readFile('packages/ui/src/components/form/field-label.tsx', 'utf8'),
    readFile('packages/ui/src/components/form/text-input.tsx', 'utf8'),
    readFile('packages/screens/src/login-screen.tsx', 'utf8'),
  ]);
  assert.match(manifest, /"build": "tamagui build --target web .* -- next build"/);
  assert.match(manifest, /"predev": "tamagui build --target web/);
  assert.match(buildConfig, /config: '\.\.\/\.\.\/packages\/ui\/src\/config\.ts'/);
  assert.match(buildConfig, /components: \['tamagui', '@project\/ui', '@project\/screens'\]/);
  assert.match(buildConfig, /outputCSS: '\.\/src\/app\/tamagui\.generated\.css'/);
  assert.match(layout, /import '\.\/tamagui\.generated\.css';/);
  assert.match(css, /--c-action-primary:#285B35/);
  assert.match(css, /\.t_light/);
  assert.match(shell, /<Button asChild><ButtonLink href="\/connexion">Se connecter<\/ButtonLink><\/Button>/);
  assert.match(nextConfig, /'react-native': 'react-native-web'/);
  assert.match(nextConfig, /allowedDevOrigins/);
  assert.match(nextConfig, /source: '\/v1\/:path\*'/);
  assert.match(button, /backgroundColor: '\$action-primary'/);
  assert.match(button, /color: '\$action-on-primary'/);
  assert.match(fieldLabel, /styled\(Label/);
  assert.match(textInput, /styled\(Input/);
  assert.match(login, /<FieldLabel htmlFor="login-email">Email<\/FieldLabel>/);
  assert.match(login, /<TextInput id="login-email"/);
});

test('les écrans partagés ne possèdent ni routeur ni couleur locale et conservent leur structure accessible', async () => {
  const { readFile } = await import('node:fs/promises');
  const source = await Promise.all([
    'app-shell.tsx',
    'login-screen.tsx',
  ].map((file) => readFile(`packages/screens/src/${file}`, 'utf8'))).then((sources) => sources.join('\n'));
  assert.match(source, /from '@project\/ui'/);
  assert.doesNotMatch(source, /(?:tamagui|next\/|react-router|expo-router|#[0-9A-Fa-f]{3,8})/);
  assert.match(source, /<SkipLink \/>/);
  assert.doesNotMatch(source, /<(?:a|button|div|form|input|label|main|p|span)\b/);
  assert.match(source, /<Screen id="main-content" role="main" aria-labelledby="shell-title">/);
  assert.match(source, /<ScreenHeader\s+id="shell-title"\s+title="Bienvenue"/);
  assert.match(source, /<ButtonLink href="\/connexion">Se connecter<\/ButtonLink>/);
  assert.equal((source.match(/<Screen\b/g) ?? []).length, 3);
});

test('les barrels ne réexportent que l API publique et les composants sont isolés', async () => {
  const { readdir, readFile } = await import('node:fs/promises');
  const ts = await import('typescript');
  const sourceFiles = [];

  async function visit(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const path = `${directory}/${entry.name}`;
      if (entry.isDirectory()) await visit(path);
      else if (/\.[cm]?[jt]sx?$/.test(entry.name)) sourceFiles.push(path);
    }
  }

  function containsJsx(node) {
    let found = false;
    const visitNode = (child) => {
      if (ts.isJsxElement(child) || ts.isJsxSelfClosingElement(child) || ts.isJsxFragment(child)) found = true;
      if (!found) ts.forEachChild(child, visitNode);
    };
    ts.forEachChild(node, visitNode);
    return found;
  }

  function componentDeclarations(source, path) {
    const file = ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true);
    const components = [];
    const visitNode = (node) => {
      if (ts.isFunctionDeclaration(node) && node.name && containsJsx(node)) components.push(node.name.text);
      if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) && node.initializer && ts.isCallExpression(node.initializer) && ts.isIdentifier(node.initializer.expression) && node.initializer.expression.text === 'styled') {
        components.push(node.name.text);
      }
      ts.forEachChild(node, visitNode);
    };
    ts.forEachChild(file, visitNode);
    return { file, components };
  }

  await Promise.all([
    visit('packages/ui/src'),
    visit('packages/screens/src'),
  ]);

  for (const path of sourceFiles) {
    const source = await readFile(path, 'utf8');
    const { file, components } = componentDeclarations(source, path);
    if (/\/index\.[cm]?[jt]sx?$/.test(path)) {
      assert.ok(file.statements.every((statement) => ts.isExportDeclaration(statement)), `${path} doit seulement réexporter`);
    } else if (path.endsWith('.tsx')) {
      assert.equal(components.length, 1, `${path} doit définir un unique composant React ou styled`);
    }
  }
});

test('le package UI est organise par responsabilite derriere son barrel public', async () => {
  const { access, readFile } = await import('node:fs/promises');
  const expectedFiles = [
    'packages/ui/src/provider/ui-provider.tsx',
    'packages/ui/src/layout/screen/screen.tsx',
    'packages/ui/src/layout/screen/screen-context.tsx',
    'packages/ui/src/layout/screen/screen-header-frame.tsx',
    'packages/ui/src/layout/screen/screen-header.tsx',
    'packages/ui/src/layout/screen/screen-title.tsx',
    'packages/ui/src/layout/screen/sticky-action-bar.tsx',
    'packages/ui/src/layout/stack/x-stack.tsx',
    'packages/ui/src/layout/stack/y-stack.tsx',
    'packages/ui/src/components/button/button.tsx',
    'packages/ui/src/components/form/field-label.tsx',
    'packages/ui/src/components/form/text-input.tsx',
    'packages/ui/src/components/typography/paragraph.tsx',
    'packages/ui/src/components/typography/text.tsx',
    'packages/ui/src/components/accessibility/focus-link.tsx',
    'packages/ui/src/components/accessibility/skip-link.tsx',
    'packages/ui/src/components/feedback/collection-notice-gate-view.tsx',
  ];
  await Promise.all(expectedFiles.map((path) => access(path)));
  const barrel = await readFile('packages/ui/src/index.tsx', 'utf8');
  for (const name of ['Button', 'Paragraph', 'Text', 'XStack', 'YStack']) {
    assert.match(barrel, new RegExp(`export \\{ ${name} \\} from './`));
  }
  assert.doesNotMatch(barrel, /from 'tamagui'/);
});

test('l’API conserve Lucid et Auth épinglés pour la persistance d identité', async () => {
  const { readFile } = await import('node:fs/promises');
  const manifest = await readFile('apps/api/package.json', 'utf8');
  assert.match(manifest, /@adonisjs\/lucid/);
  assert.match(manifest, /@adonisjs\/core/);
  assert.match(manifest, /@adonisjs\/auth/);
});
