/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'email', 'id', 'passwordHash', 'role', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare passwordHash: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmailJobSchema extends BaseModel {
  static $columns = ['accountId', 'attempts', 'availableAt', 'createdAt', 'failedAt', 'id', 'kind', 'lastError', 'lockExpiresAt', 'lockedAt', 'lockedBy', 'passwordResetTokenId', 'sentAt', 'state'] as const
  $columns = EmailJobSchema.$columns
  @column()
  declare accountId: string
  @column()
  declare attempts: number
  @column.dateTime()
  declare availableAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lockExpiresAt: DateTime | null
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare lockedBy: string | null
  @column()
  declare passwordResetTokenId: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare state: string
}

export class LoginAttemptSchema extends BaseModel {
  static $columns = ['attemptedAt', 'email', 'id', 'ip'] as const
  $columns = LoginAttemptSchema.$columns
  @column.dateTime()
  declare attemptedAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ip: string
}

export class PasswordRecoveryAttemptSchema extends BaseModel {
  static $columns = ['attemptedAt', 'email', 'id', 'ip'] as const
  $columns = PasswordRecoveryAttemptSchema.$columns
  @column.dateTime()
  declare attemptedAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ip: string
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'expiresAt', 'id', 'tokenDigest', 'usedAt'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tokenDigest: string
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class SecurityAuditProofSchema extends BaseModel {
  static $columns = ['accountId', 'action', 'id', 'occurredAt'] as const
  $columns = SecurityAuditProofSchema.$columns
  @column()
  declare accountId: string | null
  @column()
  declare action: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare occurredAt: DateTime
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}
